### ISSUE TITLE
Add size and hash of imzML/ibd files to PostgreSQL

### ISSUE THREAD

**Issue by sergii-mamedov** [metaspace2020/metaspace#1233]
To analyze the size of the datasets and the number of duplicates, I really miss two things:
 - the size of imzML and ibd files
 - hash value all these files

## Implementation steps:
  - [ ] in `_load_ds` step, add code that calculates the `md5 hash` of both files and writes this data to PostgreSQL
  - [ ] write a script that will calculate the `md5 hash` for all existing files in the S3 bucket
  - [ ] write a script that will get data on the sizes of all files in the S3 bucket
  - [ ] add the received data (size/hash) to the `dataset` table in PostgreSQL
