### ISSUE TITLE
Databases: custom, private

### ISSUE THREAD

**Issue by theodev** [metaspace2020/metaspace#150]
### TODO
- [x] engine: whitelist annotations against small databases (<1k formulas)
- [x] replace `ColocJob.molDb` field
- [x] `database -> databaseId` `molDBs -> databaseIds` updates in in sm_annotation_utils
- [x] graphql: applying annotation filters according to user access to the database
- [x] keep annotations with MSM=0 for custom databases
- [x] prepare moldbs data migration (related #576)
- [x] prepare ElasticSearch migration or reindexing
- [x] python client: add support for databases management
- [ ] engine: run experiments to estimate the maximal size of the database to be considered for whitelisting (related #527)
- [ ] database molecular images generation
- [x] update molecule to database URL mapping in `possibleCompounds`

### Deployment checklist https://github.com/metaspace2020/metaspace/issues/573

**Comment by LachlanStuart** [comment]
Notes:

### Database management

Groups should own databases (to discuss: are we all in agreement?)
    * Users can't create groups by themselves - will this be a problem? Has anyone actually contacted us to create a new group?

Names should be unique within a group, and not conflict with the official databases

### Database versions

Should we support them? There are significant difficulties in the UX if someone wants to update a database that has already had some datasets processed against.

It may be more intuitive to just not deal with versions, and advise users to suffix `-v1`, `-v2` to the name. We could add a deprecation flag so that they can hide old versions.

### Database visibility & dataset visibility

If a user wants a database private, but use it on a public dataset, which behavior do we want?
* (current behavior, i.e. least work) to show the private database annotations. Adding a warning when the database is uploaded might be enough
* to require the dataset to be set to private as soon as the database is selected
* to implement filtering annotations that use private databases

## Technical

* To minimize the changes that would be required to operate on molDB IDs everywhere, instead we'll keep using the `name` throughout the engine/graphql, format user DBs' names uniquely (e.g. `[guid]Database Name`), and split the name into `name` and `displayName` in graphql.
* Creation of molecule images
* moldb to validate and return array of `[lineno?, error/warning]` items for display to user, OR if import takes too long, email the user a report of the errors. All errors/warnings should prevent import - we don't want users cluttering the databases list with incomplete databases that were only partially imported due to errors.

**Comment by LachlanStuart** [comment]
Decisions:
* Databases should be able to be private, should not show up in public results.
* Databases are owned by groups. 
    * Users have no ability to "publish" it to the wider METASPACE community, but add a note saying to get in touch with us if they want to do so (and we can manually make it a non-group-attached database)
    * All members in a group can upload a DB
* Allow users to upload databases with the same name to overwrite old versions, with warning that it will cause old datasets to be inconsistent with new datasets unless manually reprocessed. Recommend using a different name to avoid this.
* For FDR calculation, if a database is less than ~500 molecules, add the option & a recommendation for the database to be merged with another larger database (HMDB, etc.) on upload
    * TODO: Experiment with database size to see what threshold would be best
* If database is smaller than 1000 molecules, all results will be stored regardless of FDR. Ensure that this is made very clear during database upload.
