### ISSUE TITLE
17 May release steps

### ISSUE THREAD

**Issue by intsco** [metaspace2020/metaspace#284]
- [x] Disable dataset uploads
- [x] Run DB migration script for ion image thumbnails (https://github.com/metaspace2020/metaspace/pull/248)
- [x] Run migration script for Off-sample API integration #267
- [x] Run DB migration script for optical images #299
- [x] Drop old isotopic patterns (https://github.com/metaspace2020/metaspace/pull/235)
- [x] Reprovision nginx to:
  * add routes for ion image thumbnails
  * add back moldb api route
- [x] Set feature flags to False
- [x] Set off-sample endpoint of gpu-dev instance
- [x] Deploy to prod
- [x] Enable dataset uploads

- [x] Regenerate optical images & acq_geometry #299
- [x] Generate thumbnails
- [x] Batch generate Off-sample predictions for existing datasets
- [x] Set feature flags to True
- [x] Set correct off-sample endpoint (ECS)
