### ISSUE TITLE
Deployment: Neutral Loss migration checklist

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#358]
This describes the low-downtime deployment strategy for the SQL and ElasticSearch migrations needed for the Neutral Loss changes:

- [x] Clone the SQL DB into a second DB called `sm_migration`. This DB is only used to support offline reindexing and will be thrown away afterwards
```
tmux new -s migration
sudo -u postgres psql

CREATE DATABASE sm_migration;
GRANT ALL PRIVILEGES ON DATABASE sm_migration TO sm;
\q

nice time sudo -u postgres sh -c 'pg_dump sm --exclude-table-data="graphql.coloc_*" | psql sm_migration'
```
> pg_dump took 29m37s on prod

- [x] Check out the new code into a temp directory and set it to use the second DB
```
git clone https://github.com/metaspace2020/metaspace.git ~/tmp_metaspace_migration
cd ~/tmp_metaspace_migration/metaspace/engine
git checkout master
cp /opt/dev/metaspace/metaspace/engine/conf/config.json conf/
nano conf/config.json
# Change database to sm_migration
```
> prod already had this checked out - I just pulled the latest code from origin/master and double-checked the configuration

- [x] Run the migrations scripts against `sm_migration`
```
nice time sudo -u postgres psql -d sm_migration -f migrations/r1_5_20190527_iso_image_metrics_neutral_loss.sql
# This took 16m47s on prod
source activate sm
nice time python -m migrations.r1_5_20190521_consolidate_ds_config
```
- [x] Make a new ElasticSearch index with alias `sm-inactive`
```
python -m scripts.manage_es_index --inactive create
```
- [x] Run an ElasticSearch reindex with to populate `sm-inactive`
```
nice time python -m scripts.update_es_index --inactive --ds-name "%' ORDER BY id DESC; --"
# This took 6h33m on prod
```
- [x] Activate read-only mode with message that there may be some instability
* Simultaneously do the following, which will make the system unstable but at least webapp/graphql will still be up and serving the read-only message:
    - [x] Deploy new code
    - [x] Swap `sm` and `sm-inactive` ES indexes
    - [x] Run the SQL migrations against `sm`
- [x] Deactivate read-only mode
- [x] Do an incremental reindex of ElasticSearch for all datasets from newest to oldest
- [x] Drop the `sm_migration` database
- [x] Drop the inactive ES index
```
python -m scripts.manage_es_index status
# Double-check that the correct index is active
python -m scripts.manage_es_index --inactive drop
```

**Comment by LachlanStuart** [comment]
Running through Staging:

- [/] Clone the SQL DB into a second DB called `sm_migration`. This DB is only used to support offline reindexing and will be thrown away afterwards
```
sudo -u postgres psql

CREATE DATABASE sm_migration;
GRANT ALL PRIVILEGES ON DATABASE sm_migration TO sm;
\q

nice time sudo -u postgres sh -c 'pg_dump sm --exclude-table-data="graphql.coloc_*" | psql sm_migration'
```

- [ ] Check out the new code into a temp directory and set it to use the second DB
```
git clone git@github.com:metaspace2020/metaspace.git ~/tmp_metaspace_migration
cd ~/tmp_metaspace_migration
git checkout release
cd ~/tmp_metaspace_migration/metaspace/engine
cp /opt/dev/metaspace/metaspace/engine/config/conf.json config
nano conf.json
# Change database to sm_migration
```
- [ ] Run the migrations scripts against `sm_migration` (TODO: Lachlan find out how long this takes)
```
sudo -u postgres psql -d sm_migration -f migrations/r1_5_20190527_iso_image_metrics_neutral_loss.sql
python -m migrations/r1_5_20190521_consolidate_ds_config.py
```
- [ ] Make a new ElasticSearch index with alias `sm-inactive` (TODO: Time this on Staging)
- [ ] Run an ElasticSearch reindex with to populate `sm-inactive`
- [ ] Activate read-only mode with message that there may be some instability
* Simultaneously do the following, which will make the system unstable but at least webapp/graphql will still be up and serving the read-only message:
    - [ ] Deploy new code
    - [ ] Swap `sm` and `sm-inactive` ES indexes
    - [ ] Run the SQL migrations against `sm`
- [ ] Deactivate read-only mode
- [ ] Do an incremental reindex of ElasticSearch for all datasets from newest to oldest
- [ ] Drop the `sm_migration` database
