### ISSUE TITLE
Deployment checklist

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#515]
- [x] Disable dataset processing https://metaspace2020.eu/admin/health
- [x] To prevent downtime with the webapp change, it's necessary to build the new version while the old version is still running. Run this:
```
cd /opt/dev/metaspace/metaspace/webapp
git pull
yarn install
yarn build
sudo cp --preserve -R dist /var/www/webapp
```
- [x] Apply moldb cleanup migrations
```
cd /opt/dev/metaspace/metaspace/graphql
yarn exec typeorm migration:run
cd /opt/dev/metaspace/metaspace/engine
python migrations/r1_7_20200122_moldb.py
python migrations/r1_7_20200210_moldb_v2.py
```
- [x] Reprovision nginx so that it starts serving the new webapp: `ansible-playbook -i env/prod provision/web.yml -t nginx`
- [x] Deploy as usual. `ansible-playbook -i env/prod deploy/web.yml`
- [x] Clean up the old supervisor jobs:
```
supervisorctl stop sm-web-app sm-mol-db
sudo rm /etc/supervisor/sm-web-app.supervisor /etc/supervisor/sm-mol-db-api.supervisor
```
- [x] Re-enable dataset processing https://metaspace2020.eu/admin/health
- [x] ~Rebuild ElasticSearch index so that schema changes take effect:~ (No longer needed - schema was already updated on prod manually to fix a bug with the free-text search matching isomers and isobars)
```
cd /opt/dev/metaspace/metaspace/engine
source activate sm
python -m scripts.manage_es_index status
# If there are warnings about "Could not find ElasticSearch alias" - ignore them, they're a known bug
python -m scripts.manage_es_index --inactive drop # In case the inactive index already exists
python -m scripts.manage_es_index --inactive create
nice time python -m scripts.update_es_index --inactive --ds-name "%" # This will take 16+ hours
# If the above succeeds:
python -m scripts.manage_es_index swap
```

- [x] Reindex ElasticSearch to recalculate the isobars (there was a small tweak since last deployment):
```
cd /opt/dev/metaspace/metaspace/engine
source activate sm
nice time python -m scripts.update_es_index --ds-name "%" # This will take 2+ days
```

**Comment by LachlanStuart** [comment]
From meeting: Thoroughly test mol-db changes, enable isomer/isobar feature flag and deploy to prod ASAP (ideally Wed 12 Feb)
