### ISSUE TITLE
Deployment checklist

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#566]
#### During deployment

Graphql will fail to restart due to an issue with the supervisorctl config
- [x] Run `ps aux | grep graphql` to find the orphan `node` process and `kill` it
- [x] Check `cat /etc/supervisor/sm-graphql.supervisor` and ensure that it has a `stopasgroup = true` line (this file should have been updated during deployment)
- [x] Run `supervisorctl reread` to get supervisorctl to load its updated config so that this doesn't happen again in the future

#### After deployment

- [x] Index new field:
```shell
nice time python -m scripts.update_es_index --ds-name "%' ORDER BY id DESC; --" --update-fields status_update_dt
```

- [x] Fix missing colocalization jobs. Run this on **staging**:
```shell
tmux attach -t run_coloc_on_prod_2 # Reuse this session if it still exists
cd ~/run_coloc_on_prod_2/metaspace/engine
python -m scripts.run_colocalization --fix-missing
# Press Ctrl+B, D to detach from tmux
```
