### ISSUE TITLE
Custom databases deployment checklist

### ISSUE THREAD

**Issue by intsco** [metaspace2020/metaspace#573]
# Preliminary steps:
- [x] Enable read-only mode.
- [x] Upgrade web host to a bigger instance.
- [x] Disable read-only mode.

# Deployment steps:
- [x] Checkout new version into a temp directory.
- [x] Run the database and ES migration from the temp directory.
```
time python migrations/r1_8_20200513_moldb_id_as_identifier.py \
    --config path/to/config.json
```
- [x] Check the list of datasets that failed to migrate.
- [x] **Enable read-only mode.**
- [x] Repeat the migration for new datasets and annotations.
- [x] Check all migration queries `yarn exec typeorm -- schema:log`
- [x] Deploy the new code.
- [x] Provision _nginx_: `ansible-playbook -i env/staging provision/web.yml -t nginx`
- [x] Rename the data directory: `/opt/data/sm_data` -> `/opt/data/metaspace`
- [x] Process a dataset for testing.
- [x] **Disable read-only mode.**

Resolves #309, #557.
