### ISSUE TITLE
Deployment checklist

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#733]
- [x] Update ansible env repository
- [x] Update release branch & add tag
- [x] Create AWS snapshot of prod as a backup
- [x] Verify that no datasets are currently processing and disable dataset reprocessing at https://metaspace2020.eu/admin/health with the message "METASPACE is being updated. Dataset uploads have been temporarily disabled."
- [x] `ansible-playbook -i env/prod provision/web.yml -t miniconda,ibm-cloud,sm-cluster-autostart`
- [x] `ansible-playbook -i env/prod deploy/web.yml`
- [x] Re-enable dataset reprocessing and clear the health message
- [x] Verify Spark works by uploading a test dataset at https://metaspace2020.eu/upload?feat=-lithops
- [x] Verify Lithops works by uploading a test dataset at https://metaspace2020.eu/upload?feat=lithops
- [x] Check `/opt/dev/metaspace/metaspace/engine/logs/sm-lithops-daemon.log` on the server to ensure that the Lithops job actually used Lithops
