### ISSUE TITLE
Clean up extra S3 buckets

### ISSUE THREAD

**Issue by sergii-mamedov** [metaspace2020/metaspace#824]
Now we have a number of S3 buckets that were left from various experiments or were not combined at the initial stages. I think it's worth spending a little time and merge their contents into the main dataset buckets. This will allow you to have a more consistency and spend less time on analysis. At the moment, I see the following potential buckets:

- [x] sm-engine-icl-data ([info](https://github.com/metaspace2020/private-info/issues/25#issuecomment-1437201995))
- [x] sm-engine-raw-datasets ([info](https://github.com/metaspace2020/private-info/issues/25#issuecomment-1425934489))
- [x] sm-engine-simulated-data  ([info](https://github.com/metaspace2020/private-info/issues/25#issuecomment-1419034020))
- [x] sm-engine-upload-backup
- [x] sm-engine-upload-programmatic ([info](https://github.com/metaspace2020/private-info/issues/25#issuecomment-1432832670))
- [x] sm-external-export ([info](https://github.com/metaspace2020/private-info/issues/25#issuecomment-1419092187))
