### ISSUE TITLE
TIC Images & Normalization (Front-End)

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#888]
Blocked by #885 - cannot be started until the back end is ready.

#### Show the TIC Image
- [ ] In the Dataset Overview page, add it to the diagnostics gallery
- [ ] In the Optical Image Alignment page, allow it to be selected as a reference ion image

#### TIC Normalization
- [ ] Add an additional option to the image viewer options for TIC normalization. It makes sense to put this as a "TIC normalization" checkbox under the "Intensity scaling" option in the cog menu
    * When this option is enabled, every pixel in each ion image should be divided by the value for the same pixel in the TIC image. This step should happen before hotspot removal.
    * If this option is selected and the TIC image fails to load, show an error message instead of the ion image. It's better to show nothing than show incorrect data
    * While TIC normalization is active, the "Hotspot removal" and "Outlier clipping" warning messages (when you hover over red numbers in the intensity color scale) should be changed to not refer to these values as "intensities". Ask a scientist how to describe these... maybe "relative intensities"? IDK.
    * While TIC normalization is active, the popup intensity display (when mousing over the ion image) should be changed to show both the non-normalized intensity and the normalized relative intensity.
- [ ] Add a new feature popup directing people to try it out
